### ISSUE TITLE
Elicitação - Entrevista

### ISSUE THREAD

**Issue by luis-gustavo** [Requisitos-de-Software/2019.2-Duolingo#12]
Aplicação de entrevistas para elicitação dos requisitos.

**Comment by luis-gustavo** [comment]
@luderibeiro O que acha dessas questões ?

* Você já utilizou algum outro aplicativo para aprender um idioma ? Se sim, qual ? Quais vantagens/desvantagens esse aplicativo tem em relação ao Duolingo ?

* A quanto tempo utiliza o Duolingo ?

* O que te levou a utilizar o Duolingo ?

* Que dificuldades você enfrentou ao utilizar o Duolingo ?

* Você acha que o Duolingo é suficiente para aprender um idioma ?

* Você se sente motivado(a)/engajado(a) utilizando o Duolingo ? Se sim, o que te motiva/engaja ?

* Qual foi a divisão* máxima aonde você chegou ? Qual foi o seu maior número de investidas* ?

* Quais funcionalidades você mais utiliza no Duolingo ?

* Tem alguma funcionalidade que você não gosta ou acha desnecessária ?

* Você assina ou já assinou o Duolingo Plus ? Por que o fez/não o fez ? Se já o fez, valeu a pena ?

**Comment by FranciscoHeronildo** [comment]
@luis-gustavo As questões para mim estão excelentes, mas, proponho mais uma...

**Comment by FranciscoHeronildo** [comment]
* Você já finalizou algum curso do Duolingo? Se sim, você se acha capaz de interagir com um pessoa nativa do idioma no qual você concluiu no Duolingo?

**Comment by luis-gustavo** [comment]
Adicionado @FranciscoHeronildo
