### ISSUE TITLE
Rich Picture - Configurações

### ISSUE THREAD

**Issue by vitorAlves7** [Requisitos-de-Software/2019.2-Duolingo#5]
#### Deve conter os elementos:

* Imagem
* e-mail
* compartilhar progresso
* Meta diária
* Lembrete
* Efeitos Sonoros
* mensagens motivacionais

**Comment by FranciscoHeronildo** [comment]
Foi identificado que o escopo de configurações não é prioridade da aplicação, mais é possível visualizar a diagramação na mesma no problema #1 e #3.
