### ISSUE TITLE
Refatoração - Backlog / Histórias do Usuário

### ISSUE THREAD

**Issue by FranciscoHeronildo** [Requisitos-de-Software/2019.2-Duolingo#69]
Achar uma maneira organizar a tabela do backlog do produto para fácil leitura e linkar todas as histórias de usuário

**Comment by luis-gustavo** [comment]
Adicionar metodologia e referência ao NFR

**Comment by luis-gustavo** [comment]
Adicionar "AND" ou "OR"  no topo do NFR

**Comment by FranciscoHeronildo** [comment]
O problema relacioados aos NFR's já está aberto em #68
